spring:
  profiles:
    active: dev
  application:
    name: sample-order

logging:
  config: classpath:logback-boot.xml

dubbo:
  scan:
    basePackages: com.enjoy.sample.order.api
  application:
    id: sample-order
    name: sample-order
  provider:
    filter: exceptionFilter,mybatisHelperProviderFilter,-exception
    timeout: 5000

mybatis:
  configLocation: classpath:/mybatis-config-order.xml
  mapperLocations: classpath*:/mapper/order/*Mapper.xml

server:
  servlet:
    context-path: /