spring:
  profile: test

nacos:
  config:
    server-addr: 127.0.0.1:8848
    dataIds: sample-gateway-test.yml
    type: yaml
    group: sample-gateway
    namespace: enjoy-sample-test
    bootstrap:
      enable: true