spring:
  profiles:
    active: test
  application:
    name: sample-gateway

enjoy:
  web:
    session:
      type: request
      expire: 36000
      request:
        tokenName: Access-Token
    app:
      webConfig: classpath:/routers/*
