spring:
  profile: dev
  redis:
    host: 127.0.0.1
    password: will
    port: 6379
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000

dubbo:
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    timeout: 20000
  protocol:
    port: 20016
    threads: 100

server:
  port: 8080

logging:
  config: classpath:logback-boot.xml
