spring:
  profiles:
    active: test
  application:
    name: sample-sys
  datasource:
    druid:
      filter:
        stat:
          enabled: true
          db-type: mysql
          mergeSql: true
      stat-view-servlet:
        use-global-data-source-stat: true
        enabled: true

logging:
  config: classpath:logback-boot.xml

dubbo:
  scan:
    basePackages: com.enjoy.sample.sys.api
  application:
    id: sample-sys
    name: sample-sys
  provider:
    filter: exceptionFilter,mybatisHelperProviderFilter,-exception
    timeout: 5000

server:
  servlet:
    context-path: /