spring:
  profile: dev
  profiles:
    include: userBizDev,orgBizDev
  datasource:
    druid:
      filter:
        stat:
          enabled: true
          db-type: mysql
          mergeSql: true
      stat-view-servlet:
        use-global-data-source-stat: true
        enabled: true

dubbo:
  registry:
    id: default
    address: 127.0.0.1:2181
    protocol: zookeeper
    timeout: 20000
  protocol:
    id: dubbo
    name: dubbo
    port: 20001
    threads: 100

server:
  port: 10001

logging:
  config: classpath:logback-boot.xml
